const templates = [
  {
    templateName: 'Silly 8s',
    templateCategory: 'Exercise',
    id: 1,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Rainbow hammer',
    templateCategory: 'Exercise',
    id: 2,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Third template',
    templateCategory: 'Workshop',
    id: 3,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Rainbow hammer',
    templateCategory: 'Exercise',
    id: 4,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Third template',
    templateCategory: 'Workshop',
    id: 5,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Rainbow hammer',
    templateCategory: 'Exercise',
    id: 6,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
  {
    templateName: 'Third template',
    templateCategory: 'Workshop',
    id: 7,
    imageURL: './silly8s.png',
    items: [
      { id: 1, name: '1/8', emoji: '🎱', time: 60 },
      { id: 2, name: '2/8', emoji: '🎱', time: 60 },
      { id: 3, name: '3/8', emoji: '🎱', time: 60 },
      { id: 4, name: '4/8', emoji: '🎱', time: 60 },
      { id: 5, name: '5/8', emoji: '🎱', time: 60 },
      { id: 6, name: '6/8', emoji: '🎱', time: 60 },
      { id: 7, name: '7/8', emoji: '🎱', time: 60 },
      { id: 8, name: '8/8', emoji: '🎱', time: 60 },
    ],
  },
];

export default templates;
